import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { PlayerData, PlayabilityResult } from '@/components/ClubFinderForm';

export const exportToPDF = (playerData: PlayerData, result: PlayabilityResult) => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(24);
  doc.setTextColor(34, 139, 34); // Golf green color
  doc.text('Golf Club Playability Report', 105, 20, { align: 'center' });
  
  // Add date
  doc.setFontSize(10);
  doc.setTextColor(100);
  const date = new Date().toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric' 
  });
  doc.text(`Generated on: ${date}`, 105, 28, { align: 'center' });
  
  // Playability Factor Section
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text('Playability Factor', 14, 45);
  
  // Draw a box for the score
  doc.setFillColor(34, 139, 34, 20);
  doc.roundedRect(14, 50, 182, 30, 3, 3, 'F');
  
  doc.setFontSize(36);
  doc.setTextColor(34, 139, 34);
  doc.text(result.factor.toString(), 105, 68, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text('out of 100', 105, 76, { align: 'center' });
  
  // Category badge
  doc.setFontSize(14);
  doc.setTextColor(255, 255, 255);
  doc.setFillColor(34, 139, 34);
  const categoryWidth = doc.getTextWidth(result.category) + 20;
  doc.roundedRect(105 - categoryWidth/2, 82, categoryWidth, 10, 2, 2, 'F');
  doc.text(result.category, 105, 89, { align: 'center' });
  
  // Player Data Section
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text('Your Golf Profile', 14, 105);
  
  autoTable(doc, {
    startY: 110,
    head: [['Metric', 'Value']],
    body: [
      ['Swing Speed', `${playerData.swingSpeed} mph`],
      ['Handicap', playerData.handicap.toString()],
      ['Average Distance', `${playerData.avgDistance} yards`],
      ['Play Style', playerData.playStyle.charAt(0).toUpperCase() + playerData.playStyle.slice(1)],
    ],
    theme: 'grid',
    headStyles: { fillColor: [34, 139, 34] },
    margin: { left: 14, right: 14 },
  });
  
  // Recommendations Section
  const finalY = (doc as any).lastAutoTable.finalY || 150;
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text('Recommended Golf Clubs', 14, finalY + 15);
  
  doc.setFontSize(11);
  doc.setTextColor(80);
  doc.text(
    `Based on your ${result.category.toLowerCase()} playability factor, we recommend:`,
    14,
    finalY + 23
  );
  
  autoTable(doc, {
    startY: finalY + 28,
    head: [['Club Recommendations']],
    body: result.recommendations.map(rec => [rec]),
    theme: 'striped',
    headStyles: { fillColor: [34, 139, 34] },
    margin: { left: 14, right: 14 },
  });
  
  // Add footer
  const pageCount = doc.internal.pages.length - 1;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text(
    'Generated by Golf Club Playability Calculator',
    105,
    doc.internal.pageSize.height - 10,
    { align: 'center' }
  );
  
  // Save the PDF
  doc.save(`golf-playability-report-${date.replace(/\s+/g, '-')}.pdf`);
};
